##############################
# CONFIGURATION Rules
# Release: 0.9.2
# Date: 02/02/2015
# Author: Antony Le Bechec
##############################


#MK_PATH=$(abspath $(lastword $(MAKEFILE_LIST)))
#MK_DIR_PATH=$(shell dirname $(MK_PATH))

#NGS_SCRIPTS?=$(MK_DIR_PATH)
NGSscripts?=$(NGS_SCRIPTS)
NGSEnv?=/NGS
ENV?=$(NGSscripts)/env.sh
#NGSscripts?=$(NGSEnv)/scripts
#PWD=.


# RELEASE FILE
RELEASE_FILE?=$(shell source $(ENV); echo $$RELEASE_FILE)
THREADS?=$(shell source $(ENV); echo $$THREADS)

# THREAD Calculation
#THREADS?=$(shell ls -d /sys/devices/system/cpu/cpu[[:digit:]]* | wc -w) # DYNAMIC
#THREADS?=4
#THREADS_BY_SAMPLE?=$(THREADS)


# FOLDERS
MISEQDIR?=$(MISEQ_FOLDER)
INPUTDIR?=$(DEMULTIPLEXING_FOLDER)
OUTDIR?=$(RESULTS_FOLDER)
TMP_FOLDER_TMP?=/tmp				# NGS Temporary folder
TMP_SYS_FOLDER?=/tmp				# System Temporary folder
ASSEMBLY?=hg19					# Default assembly
GENOMES?=genomes				# Genomes folder
REF?=$(GENOMES)/$(ASSEMBLY)/$(ASSEMBLY).fa	# Default Reference genome FASTA file

# OPTIONS
JAVA_MEMORY?=4
JAVA_MEMORY_BY_SAMPLE?=4
JAVA_FLAGS_TMP_FOLDER?=-Dorg.xerial.snappy.tempdir=$(TMP_FOLDER_TMP) -Djava.io.tmpdir=$(TMP_FOLDER_TMP)
JAVA_FLAGS_OTHER_PARAM?=-Dsnappy.disable=true
JAVA_FLAGS?= -Xmx$(JAVA_MEMORY)g $(JAVA_FLAGS_TMP_FOLDER) $(JAVA_FLAGS_OTHER_PARAM)
JAVA_FLAGS_BY_SAMPLE?= -Xmx$(JAVA_MEMORY_BY_SAMPLE)g $(JAVA_FLAGS_TMP_FOLDER) $(JAVA_FLAGS_OTHER_PARAM)

# DATABASES
DBFOLDER?=/media/IRCV2/NGSEnv/annovar_sources
VCFDBSNP?=$(DBFOLDER)/snp138.vcf.gz
VCFDBSNP137VCF?=$(DBFOLDER)/dbsnp_137.hg19.vcf
VCF1000G?=$(DBFOLDER)/1000G_phase1.indels.hg19.vcf
VCFMILLS1000G?=$(DBFOLDER)/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf
COSMIC?=$(DBFOLDER)/COSMIC.CodingMuts.vcf
KNOWN_ALLELES?=$(VCFMILLS1000G)
HAPMAP?=$(DBFOLDER)/hapmap_3.3.hg19.sites.vcf
OMNI?=$(DBFOLDER)/1000G_omni2.5.hg19.vcf
PHASE1_1000G?=$(DBFOLDER)/1000G_phase1.snps.high_confidence.hg19.sites.vcf


# TOOLS
FATBAM_ManifestToBED_VERSION?=$(FATBAM_VERSION)
FATBAM_BEDToOPTION_VERSION?=$(FATBAM_VERSION)
VAP_ANNOTATION_RELEASE?=$(VAP_VERSION)
VAP_PRIORITIZATION_RELEASE?=$(VAP_VERSION)
VAP_TRANSLATION_RELEASE?=$(VAP_VERSION)

# BAM Check option
BAM_CHECK_STEPS?=1

# BAM METRICS
BAM_METRICS?=1

# BAM compression
BAM_COMPRESSION?=5


# HEADER
RELEASE_CMD := $(shell echo "\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\# $(ENV_NAME) - $(ENV_DESCRIPTION)" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\# RELEASE $(ENV_RELEASE) - $(ENV_DATE) - COPYRIGHT © $(ENV_COPYRIGHT) - $(ENV_AUTHOR) ($(ENV_LICENCE) licence)" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\# CONFIG  Scripts '$(NGSscripts)' - ENV '$(ENV)' - TOOLS '$(NGSEnv)'" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#" >> $(RELEASE_INFOS) )

# RELEASE
RELEASE_CMD := $(shell echo "\#\# STARK_RELEASE: $(ENV_RELEASE)" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\#\# APP_NAME: $(APP_NAME)" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\#\# APP_RELEASE: $(APP_RELEASE)" >> $(RELEASE_INFOS) )

# GROUP/PROJECT
RELEASE_CMD := $(shell echo "\#\# GROUP: $(GROUP)" >> $(RELEASE_INFOS) )
RELEASE_CMD := $(shell echo "\#\# PROJECT: $(PROJECT)" >> $(RELEASE_INFOS) )

# INFRASTRUCTURE
RELEASE_CMD := $(shell echo "\#\# INFRASTRUCTURE: THREADS=$(THREADS), THREADS_BY_SAMPLE=$(THREADS_BY_SAMPLE), MEMORY=$(MEMORY)" >> $(RELEASE_INFOS) )

# DATABASES
RELEASE_COMMENT := "\#\# DATABASES: VCFDBSNP='$(VCFDBSNP)', VCFDBSNP137VCF='$(VCFDBSNP137VCF)', VCF1000G='$(VCF1000G)', VCFMILLS1000G='$(VCFMILLS1000G)', KNOWN_ALLELES='$(KNOWN_ALLELES)', COSMIC='$(COSMIC)'"
RELEASE_CMD := $(shell echo "$(RELEASE_COMMENT)" >> $(RELEASE_INFOS) )

# TOOLS
RELEASE_COMMENT := "\#\# TOOLS: JAVA=$(JAVA_VERSION)\&$(JAVA6_VERSION), BWA=$(BWA_VERSION), GATK=$(GATK_VERSION), SAMTOOLS=$(SAMTOOLS_VERSION), IGV=$(IGV_VERSION), IGVTOOLS=$(IGVTOOLS_VERSION), PICARD=$(PICARD_VERSION), TABIX=$(TABIX_VERSION), BCFTOOLS=$(BCFTOOLS_VERSION), VCFTOOLS=$(VCFTOOLS_VERSION), FASTQC=$(FASTQC_VERSION), FATBAM=$(FATBAM_VERSION), FATBAM_ManifestToBED=$(FATBAM_ManifestToBED_VERSION), FATBAM_BEDToOPTION=$(FATBAM_BEDToOPTION_VERSION)"
RELEASE_CMD := $(shell echo "$(RELEASE_COMMENT)" >> $(RELEASE_INFOS) )

# CONFIG/RELEASE
RELEASE_COMMENT := "\#\# CONFIG FILES: CONFIG=$(CONFIG), FUNCTIONS=$(FUNCTIONS), PARAM=$(PARAM)"
RELEASE_CMD := $(shell echo "$(RELEASE_COMMENT)" >> $(RELEASE_INFOS) )


