#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:
    

    # VARIANT BROWSER VISION
    STARK-module-VARIANTBROWSER-service-VISION:
        image: ${DOCKER_STARK_SERVICE_VARIANTBROWSER_VISION_IMAGE}
        build:
            context: ${DOCKER_STARK_SERVICE_VARIANTBROWSER_VISION_CONTEXT}
            dockerfile: Dockerfile
        container_name: ${DOCKER_STARK_SERVICE_VARIANTBROWSER_VISION_CONTAINER_NAME}
        restart: always
        env_file:
            - ${DOCKER_COMPOSE_SERVICE_VARIANTBROWSER_MODULE_ENV}
        volumes:
            # VARIANTBROWSER Config
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}/${DOCKER_STARK_MODULE}:${DOCKER_STARK_INNER_FOLDER_SERVICES}/${DOCKER_STARK_MODULE}:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}/${DOCKER_STARK_SERVICES_FOLDER_VARIANTBROWSER_VISION}:${DOCKER_STARK_INNER_FOLDER_SERVICES}/${DOCKER_STARK_SERVICES_FOLDER_VARIANTBROWSER_VISION}:rw    
            # HOWARD databases defintions (if already exists)
            #- ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG_HOWARD}:${DOCKER_STARK_INNER_FOLDER_CONFIG_HOWARD}:ro        
        ports:
            - ${DOCKER_STARK_SERVICE_PORT_PATTERN}${DOCKER_STARK_SERVICE_VARIANTBROWSER_VISION_PORT}:${DOCKER_STARK_SERVICE_VARIANTBROWSER_VISION_PORT_INNER}
        networks:
            - ${DOCKER_VARIANTBROWSER_NETWORK}
            - stark_stark


# NETWORK
###########

networks:

    stark_stark:
        external: true

    variantbrowser:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_STARK_SERVICE_SUBNET_PATTERN}${DOCKER_STARK_SERVICE_VARIANTBROWSER_SUBNET}
                #  gateway: ${DOCKER_STARK_SERVICE_SUBNET_PATTERN}${DOCKER_STARK_SERVICE_VARIANTBROWSER_GATEWAY}


