#########
# STARK #
#########
# Usage: docker-compose up


version: '3'


# SERVICES
##########

services:

    # STARK IMAGES
    ##############

    # STARK IMAGE

    stark:
        image: ${DOCKER_STARK_IMAGE}
        build:
            context: ${DOCKER_STARK_CONTEXT}
            dockerfile: Dockerfile
            args:
                - DOCKER_STARK_IMAGE_BASE=${DOCKER_STARK_IMAGE_BASE}
        env_file:
            - .env
        links:
            - stark-base

    # STARK BASE IMAGE

    stark-base:
        image: ${DOCKER_STARK_IMAGE_BASE}
        build:
            context: ${DOCKER_STARK_CONTEXT}
            dockerfile: base.Dockerfile
        env_file:
            - .env

    # STARK DATABASES POPULATION

    stark-databases:
        image: ${DOCKER_STARK_IMAGE}
        entrypoint: /tool/toolbox/get_databases.sh
        command: --build --threads=${DOCKER_STARK_GET_DATABASES_THREADS} --additional_annotations=${DOCKER_STARK_GET_DATABASES_ADDITIONAL_ANNOTATIONS}
        volumes:
            - databases:/STARK/databases
        links:
            - stark


    # SERVICES
    ##########

    # STARK SERVICE SERVER

    stark-server:
        image: ${DOCKER_STARK_IMAGE_SERVICE_SERVER}
        build:
            context: ${DOCKER_STARK_CONTEXT}service/server
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - ${DOCKER_STARK_SERVICE_SERVER_PORT_HOST}:${DOCKER_STARK_SERVICE_SERVER_PORT_INNER}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - analyses:/STARK/analyses
        links:
            - stark
            - stark-databases

    # STARK SERVICE SERVER CENTOS

    stark-server-centos:
        image: ${DOCKER_STARK_IMAGE_SERVICE_SERVER}-centos
        build:
            context: ${DOCKER_STARK_CONTEXT}service/server
            dockerfile: centos.Dockerfile
        env_file:
            - .env
        ports:
            - ${DOCKER_STARK_SERVICE_SERVER_PORT_HOST}02:${DOCKER_STARK_SERVICE_SERVER_PORT_INNER}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - analyses:/STARK/analyses
        links:
            - stark
            - stark-databases


# VOLUMES
#########

volumes:

    # ANALYSES

    analyses:
        driver: local
        driver_opts:
            type: none
            device: ${DOCKER_STARK_FOLDER_ANALYSES}
            o: bind

    # DATABASES

    databases:
        driver: local
        driver_opts:
            type: none
            device: ${DOCKER_STARK_FOLDER_DATABASES}
            o: bind
