#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:


    # STARK IMAGES
    ##############


    # STARK SOURCES
    stark-sources:
        image: ${DOCKER_STARK_SOURCES_IMAGE}
        build:
            context: ${DOCKER_STARK_IMAGE_CONTEXT}
            dockerfile: Dockerfile
            args:
                - THREADS=${DOCKER_STARK_BUILD_THREADS}
                - REPO_SOURCES=${DOCKER_STARK_BUILD_SOURCES_URL}
                - REMOVE_SOURCES=0
        container_name: STARK-sources
        command: --help
        networks:
            - stark


    # STARK IMAGE
    stark:
        image: ${DOCKER_STARK_IMAGE}
        build:
            context: ${DOCKER_STARK_IMAGE_CONTEXT}
            dockerfile: Dockerfile
            args:
                - THREADS=${DOCKER_STARK_BUILD_THREADS}
                - REPO_SOURCES=${DOCKER_STARK_BUILD_SOURCES_URL}
                - REMOVE_SOURCES=1
        container_name: STARK
        command: --help
        depends_on:
            - stark-sources
        networks:
            - stark


    # STARK SETUP
    stark-setup:
        image: ${DOCKER_STARK_IMAGE}
        container_name: STARK-setup
        entrypoint: /bin/bash
        command: -c "/tool/bin/STARK.setup --docker-env-file=/tool/.env --setup-type=INNER --setup-main-folder-pattern=/STARK_folder_setup --verbose"
        volumes:
            - ${DOCKER_STARK_MAIN_FOLDER}:/STARK_folder_setup/STARK:rw
            - ${DOCKER_COMPOSE_ENV}:/tool/.env:ro
        depends_on:
            - stark
        networks:
            - stark


    # STARK DATABASES POPULATION
    stark-databases:
        image: ${DOCKER_STARK_IMAGE}
        container_name: STARK-databases
        entrypoint: /bin/bash
        command: -c "/tool/bin/get_databases.sh --build --current --databases=${DOCKER_STARK_INNER_FOLDER_DATABASES} --threads=${DOCKER_STARK_GET_DATABASES_THREADS} --databases_list=ALL --additional_annotations=${DOCKER_STARK_GET_DATABASES_ADDITIONAL_ANNOTATIONS} --verbose 1>>${DOCKER_STARK_INNER_FOLDER_DATABASES}/STARK.databases.build.log 2>>${DOCKER_STARK_INNER_FOLDER_DATABASES}/STARK.databases.build.err"
        volumes:
            # Databases folder
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_INNER_FOLDER_DATABASES}:rw
            # HOWARD databases defintions (if already exists, need to define DOCKER_STARK_FOLDER_CONFIG_HOWARD and DOCKER_STARK_INNER_FOLDER_CONFIG_HOWARD)
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG_HOWARD}:${DOCKER_STARK_INNER_FOLDER_CONFIG_HOWARD}:ro
        depends_on:
            - stark
            - stark-setup
        networks:
            - stark


    # STARK SOURCES
    stark-sources-archives:
        image: ${DOCKER_STARK_SOURCES_IMAGE}
        container_name: STARK-sources-archives
        entrypoint: /bin/bash
        command: -c "rsync -auczAXhiv --no-links --no-perms --no-owner --no-group ${DOCKER_STARK_INNER_FOLDER_SOURCES}/* /sources-archives/ 1>>/sources-archives/archives.log 2>>/sources-archives/archives.err && rsync -auczAXhiv --no-links --no-perms --no-owner --no-group ${DOCKER_STARK_INNER_FOLDER_MAIN}/tools/* /sources-archives/sources/tools/ 1>>/sources-archives/archives.log 2>>/sources-archives/archives.err "
        volumes:
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SOURCES}:/sources-archives:rw
        depends_on:
            - stark-sources
            - stark-setup
        networks:
            - stark

            
# NETWORK
###########

networks:
    stark:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_STARK_MAIN_SUBNET}
                #  gateway: ${DOCKER_STARK_MAIN_GATEWAY}

