#########
# STARK #
#########
# Usage: docker-compose up


version: '3'


# SERVICES
##########

services:

    # STARK IMAGES
    ##############

    # STARK IMAGE

    stark:
        image: ${DOCKER_STARK_IMAGE}
        build:
            context: ${DOCKER_STARK_CONTEXT}
            dockerfile: Dockerfile
            args:
                - DOCKER_STARK_IMAGE_BASE=${DOCKER_STARK_IMAGE_BASE}
        container_name: STARK
        env_file:
            - .env
        links:
            - stark-base

    # STARK BASE IMAGE

    stark-base:
        image: ${DOCKER_STARK_IMAGE_BASE}
        build:
            context: ${DOCKER_STARK_CONTEXT}
            #dockerfile: base.Dockerfile
            dockerfile: repo.Dockerfile
            args:
                - REMOVE_SOURCE=1
                - REPO=${DOCKER_STARK_BUILD_REPO_URL}
        container_name: STARK-base
        depends_on:
            - stark-server-repo
        env_file:
            - .env
        links:
            - stark-server-repo

    # STARK DATABASES POPULATION

    stark-databases:
        image: ${DOCKER_STARK_IMAGE}
        entrypoint: /tool/bin/get_databases.sh
        command: --build --threads=${DOCKER_STARK_GET_DATABASES_THREADS} --additional_annotations=${DOCKER_STARK_GET_DATABASES_ADDITIONAL_ANNOTATIONS}
        container_name: STARK-databases
        volumes:
            - databases:/STARK/databases
        links:
            - stark

    # STARK REPO

    stark-repo:
        image: ${DOCKER_STARK_IMAGE_BASE}
        build:
            context: ${DOCKER_STARK_CONTEXT}
            #dockerfile: base.Dockerfile
            dockerfile: repo.Dockerfile
            args:
                - REMOVE_SOURCE=0
                - REPO=${DOCKER_STARK_BUILD_REPO_URL}
        entrypoint: bash
        command: -c "find /STARK/sources/sources/ -maxdepth 3 -mindepth 1 -type d"
        container_name: STARK-repo
        depends_on:
            - "stark-server-repo"
        env_file:
            - .env
        #links:
        #    - stark-server-repo


    # SERVICES
    ##########

    # STARK SERVICE SERVER

    stark-server-launcher:
        image: ${DOCKER_STARK_IMAGE_SERVICE_SERVER}
        build:
            context: ${DOCKER_STARK_CONTEXT}service/server
            dockerfile: Dockerfile
        container_name: STARK-server-launcher
        env_file:
            - .env
        ports:
            - ${DOCKER_STARK_SERVICE_SERVER_PORT_HOST}:${DOCKER_STARK_SERVICE_SERVER_PORT_INNER}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - analyses:/STARK/analyses
        links:
            - stark
            - stark-databases

    # STARK SERVICE SERVER CENTOS

    stark-server-launcher-centos:
        image: ${DOCKER_STARK_IMAGE_SERVICE_SERVER}-centos
        build:
            context: ${DOCKER_STARK_CONTEXT}service/server
            dockerfile: centos.Dockerfile
        container_name: STARK-server-launcher-centos
        env_file:
            - .env
        ports:
            - ${DOCKER_STARK_SERVICE_SERVER_PORT_HOST}02:${DOCKER_STARK_SERVICE_SERVER_PORT_INNER}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - analyses:/STARK/analyses
        links:
            - stark
            - stark-databases

    # STARK SERVICE REPO

    stark-server-repo:
        image: ${DOCKER_STARK_SERVICE_REPO_IMAGE}
        container_name: STARK-server-repo
        restart: always
        env_file:
            - .env
        ports:
            - ${DOCKER_STARK_SERVICE_REPO_PORT_HOST}:${DOCKER_STARK_SERVICE_REPO_PORT_INNER}
        volumes:
            - ${DOCKER_STARK_SERVICE_REPO_FOLDER}:/usr/local/apache2/htdocs/
        restart: always




# VOLUMES
#########

volumes:

    # ANALYSES

    analyses:
        driver: local
        driver_opts:
            type: none
            device: ${DOCKER_STARK_FOLDER_ANALYSES}
            o: bind

    # DATABASES

    databases:
        driver: local
        driver_opts:
            type: none
            device: ${DOCKER_STARK_FOLDER_DATABASES}
            o: bind
