[metadata]
name = starkub
version = 0.1.0
description = STARK Mini Kubernetes API
long_description = file: README.md
long_description_content_type = text/markdown
author = STARK Team
author_email = antony.lebechec@chru-strasbourg.fr
url = https://github.com/bioinfo-chru-strasbourg/STARK.git
license_files = LICENSE
keywords = bioinformatics, network, task management, kubernetes, api

[options]
packages = find:
install_requires =
    fastapi
    python-jose[cryptography]
    passlib[bcrypt]
    uvicorn
    python-multipart
    jinja2
    httpx
