#!/bin/bash
#################################
## STARK environment
#################################

# APPLICATION INFOS
#####################
APP_NAME=""
APP_RELEASE=""
APP_DESCRIPTION=""
APP_GROUP=""
APP_PROJECT=""



# VARIABLE INITIALISATION
############################

APP_NAME=""
APP_GROUP=""
APP_PROJECT=""

# RULES for APP
RULES_APP=""
RULES=""

# FILE to provide in folder repository
RESULTS_SUBFOLDER_ROOT_FILE_PATTERNS=""

# PIPELINES
PIPELINES=""
ALIGNERS=""
CALLERS=""
ANNOTATORS=""

# PANEL/MANIFEST/BED
MANIFEST=""
BED=""


# HOWARD FILTER DEFAULT
HOWARD2_PRIORITIZATION_DEFAULT="default"
HOWARD2_PRIORITIZATION_REPORT="default"
#HOWARD_PRIORITIZATION_MINIMUM="default"
#ANNOVAR_DATABASES=""
#SNPEFF_DATABASES=""

# SYSTEM Config
export LANG=C
