#!/bin/bash
## STARK env for HUSTUMSOL.MTPTHS RUNs

# DEFAULT ENV
######################
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )/env.ONCO.sh

# APPLICATION INFOS
#####################

APP_NAME="HUSTUMSOL"
APP_RELEASE="1.0"

GROUP="HUSTUMSOL"
PROJECT="UNKNOWN"


# ANALYSIS PARAMETERS
#######################

# ALIGNERS
ALIGNERS="bwamem"

# CALLERS
CALLERS="gatkHC_HUSTUMSOL gatkUG_HUSTUMSOL  VarScan_HUSTUMSOL canoes" # samtools_HUSTUMSOL gatkHC_HUSTUMSOL

# ANNOTATORS
ANNOTATORS="howard"

# PIPELINES
PIPELINES=""


# HOWARD FILTER
################
HOWARD_PRIORITIZATION="TUMSOL,SOLIDTUMOR"
HOWARD_PRIORITIZATION_MINIMAL="TUMSOL,SOLIDTUMOR"
HOWARD_PRIORITIZATION_REPORT="TUMSOL,SOLIDTUMOR"

# COVERAGE CRITERIA (default "1,30")
COVERAGE_CRITERIA="1,300,1000"


# FOOTER
###########
#source $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )/env_footer.sh
source $STARK_FOLDER/env_footer.sh



