#########
# STARK #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:


    # EDITH DASHBOARD
    STARK-module-EDITH-service-dashboard:
        image: ${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_IMAGE}
        build:
            context: ${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_CONTEXT}
            dockerfile: Dockerfile
        container_name: ${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_CONTAINER_NAME}
        restart: always
        env_file:
            - ${DOCKER_COMPOSE_SERVICE_EDITH_MODULE_ENV}
        environment:
            - FOLDER_SERVICES=${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_SERVICES}
            - FOLDER_INPUTS=${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_INPUTS}
            - FOLDER_REPOSITORIES=${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_REPOSITORIES}
            - FOLDER_API=${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_SERVICES}/STARK/API
            - FOLDER_LISTENER=${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_SERVICES}/STARK/listener
            - URI_API=  # will find STARK/API service and construct URI
        volumes:
            # Docker sock - if sock access ok
            #- /var/run/docker.sock:/var/run/docker.sock
            # EDITH dashboard Config
            #- ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_CONFIG}/${DOCKER_STARK_SERVICES_FOLDER_EDITH_DASHBOARD}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_CONFIG}:ro
            # Data folders available (need to be coherent with other services)
            # Services
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_SERVICES}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_DATA}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PUBLIC_DIR}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_SERVICES}:rw
            # Databases
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATABASES}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_DATA}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PUBLIC_DIR}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_DATABASES}:ro
            # Input
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_DATA}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_DATA}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PUBLIC_DIR}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_INPUTS}/Data:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_INPUT}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_DATA}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PUBLIC_DIR}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_INPUTS}/Input:ro
            # Output
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_REPOSITORY}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_DATA}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PUBLIC_DIR}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_REPOSITORIES}/Repository:ro
            - ${DOCKER_STARK_MAIN_FOLDER}/${DOCKER_STARK_FOLDER_OUTPUT_ARCHIVE}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_INNER_FOLDER_DATA}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PUBLIC_DIR}/${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_SUBFOLDER_REPOSITORIES}/Archive:ro
        ports:
            - ${DOCKER_STARK_SERVICE_PORT_PATTERN}${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PORT}:${DOCKER_STARK_SERVICE_EDITH_DASHBOARD_PORT_INNER}
        networks:
            - ${DOCKER_EDITH_NETWORK}
            - stark_stark



# NETWORK
###########

networks:
    
    stark_stark:
        external: true
    
    edith:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_STARK_SERVICE_SUBNET_PATTERN}${DOCKER_STARK_SERVICE_EDITH_SUBNET}
                #  gateway: ${DOCKER_STARK_SERVICE_SUBNET_PATTERN}${DOCKER_STARK_SERVICE_EDITH_GATEWAY}

    