#!/bin/bash
## STARK application ONCO

# DEFAULT ENV
######################
source_app "HUSDIAGGEN"

# APPLICATION INFOS
#####################
APP_NAME="HUSDIAGGEN.DIGGYNECOL0705491"
APP_RELEASE="1.0"
APP_GROUP="HUSDIAGGEN"
APP_PROJECT="DIGGYNECOL0705491"


# ANALYSIS PARAMETERS
#######################
